language: python

python:
- '3.6'

cache: pip

branches:
  except:
    - master

services:
- postgresql

addons:
  postgresql: "9.4"

install:
- export TRAVIS_HOME=`pwd`
- pip install -e .
- cd tests/data
- python pytest_initdb.py --host 127.0.0.1 --port 5432 --user postgres --connect-db postgres --database travis
- cd $TRAVIS_HOME

script:
- LZAPI_MODE="travis" pytest tests
