version: '3'

volumes:
  pgdata: {}
  lzvol: {}
  redisvol: {}

services:
  api:
    build:
      context: .
      args:
        - LZAPI_VERSION
        - GIT_SHA
    image: "locuszoom-api"
    env_file:
      - .env
    ports:
      - "${LZAPI_PORT}:${LZAPI_PORT}"
    volumes:
      - lzvol:/home/locuszoom-api
      - ./etc:/home/locuszoom-api/etc
    depends_on:
      - redis
      - postgres
    working_dir: /home/locuszoom-api
    command: python3 bin/run_gunicorn.py

  postgres:
    image: "postgres:9.4"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: "redis:5.0.7"
    volumes:
      - redisvol:/data
